library(lme4)
library(dplyr)
library(tidyverse)
library(AER)
library(MASS)
library(ggplot2)
library(gridExtra)
library(knitr)

set.seed(123)

df <- read.csv("/Users/aliyahaas/Desktop/STAT437/heart_failure_clinical_records_dataset.csv")
head(df)

range(df$platelets)
set.seed(123)

## GLMM with Poisson and Log link function

df$age_group <- cut(
  df$age,
  breaks = c(39, 55, 70, 95),
  labels = c("40-55", "56-70", "71-95"),
  include.lowest = TRUE
)

df$platelet_group <- cut(
  df$platelets,
  breaks = quantile(df$platelets, probs = c(0, 0.33, 0.66, 1), na.rm = TRUE),
  labels = c("Low", "Mid", "High"),
  include.lowest = TRUE
)

df$ef_group <- cut(
  df$ejection_fraction,
  breaks = c(0, 40, 60, 100),
  labels = c("LowEF", "MidEF", "HighEF"),
  include.lowest = TRUE
)


library(dplyr)

df_grouped <- df %>%
  group_by(age_group, sex, platelet_group, ef_group) %>%
  summarise(
    n_patients = n(),
    death_count = sum(DEATH_EVENT),
    .groups = "drop"
  )

print(df_grouped)

df_grouped$cluster <- interaction(
  df_grouped$age_group,
  df_grouped$sex
)

library(lme4)

model_glmm <- glmer(
  death_count ~ platelet_group + ef_group +
    offset(log(n_patients)) +
    (1 | cluster),
  family = poisson(link = "log"),
  data = df_grouped,
  control = glmerControl(optimizer = "bobyqa")
)


summary(model_glmm)


# Gaussian with linear function
df <- df %>%
  mutate(time_group = cut(
    time,
    breaks = c(4, 38, 73, 143, 213, 248, 285),
    labels = c("4-38", "39-73", "74-143", "144-213", "214-248", "249-284"),
    include.lowest = TRUE
  ))

df$cluster <- interaction(df$age_group, df$sex)
df$serum_creatinine <- scale(df$serum_creatinine)

library(lme4)
df$serum_creatinine <- scale(df$serum_creatinine)

model_glmm_gaussian <- lmer(
  serum_creatinine ~ age_group * time_group + platelet_group + sex +
    (1 | cluster),
  data = df
)

summary(model_glmm_gaussian)

