library(lme4)
library(dplyr)
library(tidyverse)
library(AER)
library(MASS)
library(ggplot2)
library(gridExtra)
library(knitr)

set.seed(123)

df <- read.csv("/Users/aliyahaas/Desktop/STAT437/heart_failure_clinical_records_dataset.csv")
head(df)

range(df$platelets)
set.seed(123)

## GLMM with Poisson and Log link function

df$age_group <- cut(
  df$age,
  breaks = c(39, 55, 70, 95),
  labels = c("40-55", "56-70", "71-95"),
  include.lowest = TRUE
)

df$platelet_group <- cut(
  df$platelets,
  breaks = quantile(df$platelets, probs = c(0, 0.33, 0.66, 1), na.rm = TRUE),
  labels = c("Low", "Mid", "High"),
  include.lowest = TRUE
)

df$ef_group <- cut(
  df$ejection_fraction,
  breaks = c(0, 40, 60, 100),
  labels = c("LowEF", "MidEF", "HighEF"),
  include.lowest = TRUE
)


library(dplyr)

df_grouped <- df %>%
  group_by(age_group, sex, platelet_group, ef_group) %>%
  summarise(
    n_patients = n(),
    death_count = sum(DEATH_EVENT),
    .groups = "drop"
  )

print(df_grouped)

df_grouped$cluster <- interaction(
  df_grouped$age_group,
  df_grouped$sex
)

library(lme4)

model_glmm <- glmer(
  death_count ~ platelet_group + ef_group +
    offset(log(n_patients)) +
    (1 | cluster),
  family = poisson(link = "log"),
  data = df_grouped,
  control = glmerControl(optimizer = "bobyqa")
)


summary(model_glmm)


# Gaussian with linear function
df <- df %>%
  mutate(time_group = cut(
    time,
    breaks = c(4, 38, 73, 143, 213, 248, 285),
    labels = c("4-38", "39-73", "74-143", "144-213", "214-248", "249-284"),
    include.lowest = TRUE
  ))

df$cluster <- interaction(df$age_group, df$sex)
df$serum_creatinine <- scale(df$serum_creatinine)

library(lme4)
df$serum_creatinine <- scale(df$serum_creatinine)

model_glmm_gaussian <- lmer(
  serum_creatinine ~ age_group * time_group + platelet_group + sex +
    (1 | cluster),
  data = df
)

summary(model_glmm_gaussian)

#Binomail GLMM

binomial_glmm <- glmer(
  DEATH_EVENT ~ ejection_fraction +
                serum_creatinine +
                serum_sodium +
                creatinine_phosphokinase +
                platelets +
                anaemia +
                diabetes +
                high_blood_pressure +
                sex +
                smoking +
                time +
                (1 | age_group), 
  data    = df,
  family  = binomial(link = "logit"),
  control = glmerControl(optimizer = "bobyqa",
                         optCtrl   = list(maxfun = 2e5),
                         autoscale = TRUE)
)
 
summary(binomial_glmm)


# Survival Analysis
surv_obj <- Surv(time = df$time, event = df$DEATH_EVENT)
 
# Kaplan-Meier by age group
km_age <- survfit(surv_obj ~ age_group, data = df)
 
p_km_age <- ggsurvplot(km_age,
  data         = df,
  pval         = TRUE,
  conf.int     = TRUE,
  risk.table   = TRUE,
  palette      = c("#2E86AB", "#F4A261", "#E84855", "#57CC99"),
  title        = "Kaplan-Meier Survival Curves by Age Group",
  xlab         = "Follow-up Time (Days)",
  ylab         = "Survival Probability",
  legend.title = "Age Group",
  ggtheme      = theme_minimal(base_size = 12)
)

print(p_km_age)

km_sex <- survfit(surv_obj ~ sex, data = df)
 
p_km_sex <- ggsurvplot(km_sex,
  data         = df,
  pval         = TRUE,
  conf.int     = TRUE,
  risk.table   = TRUE,
  palette      = c("#E84855", "#2E86AB"),
  title        = "Kaplan-Meier Survival Curves by Sex",
  xlab         = "Follow-up Time (Days)",
  ylab         = "Survival Probability",
  legend.title = "Sex",
  ggtheme      = theme_minimal(base_size = 12)
)
 
p_km_sex
km_plt <- survfit(surv_obj ~ platelet_group, data = df)
 
p_km_plt <- ggsurvplot(km_plt,
  data         = df,
  pval         = TRUE,
  conf.int     = TRUE,
  risk.table   = TRUE,
  palette      = c("#E84855", "#2E86AB", "#F4A261"),
  title        = "Kaplan-Meier Survival Curves by Platelet Group",
  xlab         = "Follow-up Time (Days)",
  ylab         = "Survival Probability",
  legend.title = "Platelet Group",
  ggtheme      = theme_minimal(base_size = 12)
)

p_km_plt

#Cox
new.cox <- coxph(Surv(time, DEATH_EVENT) ~ age + anaemia + creatinine_phosphokinase + diabetes + ejection_fraction + high_blood_pressure + platelets + serum_creatinine + serum_sodium + sex + smoking, data = df)

summary(new.cox)

new.cox.tab <- tidy(new.cox, exponentiate = T, conf.int=T)

new.cox.tab

#Predict survival function
surv.at.means <- survfit(new.cox) 
tidy(surv.at.means)
plotdataz
plot(surv.at.means, xlab="days", ylab="survival probability")

